# Generated by Django 4.2.9 on 2024-09-21 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_birthday_user_gender_teacher_student_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="user",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                ],
                default="user",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="students",
            field=models.ManyToManyField(
                limit_choices_to={"role": "student"},
                related_name="student_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="teacher",
            field=models.ForeignKey(
                limit_choices_to={"role": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
