# Generated by Django 4.2.9 on 2024-09-21 09:48

import ckeditor.fields
import common.storages
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('category', models.IntegerField(choices=[(1, 'CompetitiveProgramming'), (2, 'Technologies'), (3, 'Math'), (4, 'IQ')])),
                ('logo', models.ImageField(blank=True, null=True, storage=common.storages.ContestLogoStorage, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_time',),
            },
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('penalties', models.IntegerField(default=0)),
                ('rank', models.IntegerField(null=True)),
                ('rating', models.IntegerField()),
                ('seed', models.FloatField(default=0.0)),
                ('delta', models.IntegerField(default=0)),
                ('perfomance', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['contest', '-points', 'penalties', 'user'],
            },
        ),
        migrations.CreateModel(
            name='ContestsRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contests_rating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating'],
            },
            managers=[
                ('ratings', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('ball', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='contests.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
            ],
            options={
                'ordering': ['symbol'],
            },
            managers=[
                ('problems', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ContestantProblemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('penalties', models.IntegerField(default=0)),
                ('attempts_count', models.IntegerField(default=0)),
                ('first_accepted_time', models.DateTimeField(blank=True, null=True)),
                ('the_best', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contest_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestants_info', to='contests.contestproblem')),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems_info', to='contests.contestant')),
            ],
            options={
                'ordering': ['contestant'],
                'unique_together': {('contestant', 'contest_problem')},
            },
            managers=[
                ('problems', django.db.models.manager.Manager()),
            ],
        ),
    ]
